version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./api/chatbot.db:/app/chatbot.db
    networks:
      - chatbot-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge
